# Generated by Django 5.0.2 on 2024-02-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('fiz_lico', models.BooleanField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('fiz_lico', models.BooleanField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('seller', models.BooleanField(default=False)),
                ('buyer', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
