# Generated by Django 5.0.2 on 2024-03-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_bank_operation_mybankaccount_partnerbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytestdoc1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('doc_date', models.DateTimeField()),
                ('summa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mytesttab1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.mytestdoc1')),
            ],
        ),
    ]
