# Generated by Django 5.0.2 on 2024-03-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_mytestdoc1_mytesttab1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('doc_date', models.DateTimeField()),
                ('my_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_doc', to='office.mycompany')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_doc', to='office.operation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TabDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='mytesttab1',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='office.mytestdoc1'),
        ),
        migrations.CreateModel(
            name='BankDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('doc_date', models.DateTimeField()),
                ('my_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='office.mycompany')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc', to='office.operation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemainingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=3, max_digits=6)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='office.tradedoc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='office.product')),
                ('str_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='office.tabdoc')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOfGood',
            fields=[
                ('tradedoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.tradedoc')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='office.partner')),
            ],
            options={
                'abstract': False,
            },
            bases=('office.tradedoc',),
        ),
        migrations.CreateModel(
            name='SaleOfGood',
            fields=[
                ('tradedoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.tradedoc')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='office.partner')),
            ],
            options={
                'abstract': False,
            },
            bases=('office.tradedoc',),
        ),
        migrations.CreateModel(
            name='StrOfTabPurchaseOfGood',
            fields=[
                ('tabdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.tabdoc')),
                ('count', models.DecimalField(decimal_places=3, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='str_purchase', to='office.purchaseofgood')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='str_purchase', to='office.product')),
            ],
            bases=('office.tabdoc',),
        ),
        migrations.CreateModel(
            name='StrOfTabSaleOfGood',
            fields=[
                ('tabdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.tabdoc')),
                ('count', models.DecimalField(decimal_places=3, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='str_sale', to='office.saleofgood')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='str_sale', to='office.product')),
            ],
            bases=('office.tabdoc',),
        ),
    ]
